// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YolArkadashim.API.Data;

#nullable disable

namespace YolArkadashim.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YolArkadashim.API.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("MatchRequestId")
                        .IsUnique();

                    b.HasIndex("RiderId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviationRadiusMeters")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EveningDepartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FlexibilityDaysPct")
                        .HasColumnType("integer");

                    b.Property<string>("FlexibilityNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HomeAddressText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Point>("HomeLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<TimeOnly>("MorningDepartTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("PricePerTrip")
                        .HasColumnType("decimal(8,2)");

                    b.Property<LineString>("RoutePolyline")
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkAddressText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Point>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeLocation"), "GIST");

                    b.HasIndex("RoutePolyline");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RoutePolyline"), "GIST");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WorkLocation"), "GIST");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.MatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ContactSharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RiderProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("RiderId");

                    b.HasIndex("RiderProfileId");

                    b.ToTable("MatchRequests");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.RiderProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HomeAddressText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Point>("HomeLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<TimeOnly>("PreferredDepartFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("PreferredDepartTo")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkAddressText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Point>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeLocation"), "GIST");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WorkLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WorkLocation"), "GIST");

                    b.ToTable("RiderProfiles");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailNotify")
                        .HasColumnType("boolean");

                    b.Property<string>("HomeAddressText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("HomeLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkAddressText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("WorkLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.HasKey("Id");

                    b.HasIndex("HomeLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeLocation"), "GIST");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WorkLocation"), "GIST");

                    b.ToTable("SavedSearches");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedTermsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmailVerifyCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerifyExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTcVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TcVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Plate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Conversation", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YolArkadashim.API.Models.MatchRequest", "MatchRequest")
                        .WithOne("Conversation")
                        .HasForeignKey("YolArkadashim.API.Models.Conversation", "MatchRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YolArkadashim.API.Models.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("MatchRequest");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Listing", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "User")
                        .WithMany("Listings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.MatchRequest", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.Listing", "Listing")
                        .WithMany("MatchRequests")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YolArkadashim.API.Models.User", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YolArkadashim.API.Models.RiderProfile", null)
                        .WithMany("MatchRequests")
                        .HasForeignKey("RiderProfileId");

                    b.Navigation("Listing");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Message", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YolArkadashim.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Notification", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Report", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.RiderProfile", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "User")
                        .WithOne("RiderProfile")
                        .HasForeignKey("YolArkadashim.API.Models.RiderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.SavedSearch", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Vehicle", b =>
                {
                    b.HasOne("YolArkadashim.API.Models.User", "User")
                        .WithOne("Vehicle")
                        .HasForeignKey("YolArkadashim.API.Models.Vehicle", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.Listing", b =>
                {
                    b.Navigation("MatchRequests");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.MatchRequest", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.RiderProfile", b =>
                {
                    b.Navigation("MatchRequests");
                });

            modelBuilder.Entity("YolArkadashim.API.Models.User", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("RiderProfile");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
